.TH "HARDN-XDR" 1 "July 29, 2025" "1.1.161" "HARDN-XDR User Manuals"
.SH NAME
hardn-xdr \- Linux Security Hardening Tool
.SH SYNOPSIS
.B hardn-xdr
[\fI--version\fR | \fI-v\fR]
[\fI--help\fR | \fI-h\fR]
[\fI--test\fR]
.SH DESCRIPTION
\fBHARDN-XDR\fR is a Linux security hardening and endpoint defense toolkit.
This simplified version provides basic system information and serves as a foundation for security hardening tools.
.SH OPTIONS
.TP
\fB--version, -v\fR
Displays the version of HARDN-XDR.
.TP
\fB--help, -h\fR
Shows help information and usage.
.TP
\fB--test\fR
Runs basic system checks.
.SH EXAMPLES
.TP
\fBhardn-xdr --help\fR
Display help information.
.TP
\fBhardn-xdr --test\fR
Run basic system checks.
.SH AUTHOR
Tim Burns <control@cybersynapse.ro>
.SH COPYRIGHT
Copyright (C) 2025 OpenSource-For-Freedom. This is free software; see the source for copying conditions.