# Dependabot configuration for HARDN

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "python" # Ecosystem for Python dependencies
    directory: "/" 
    schedule:
      interval: "weekly" 
      time: "02:00" # Time in UTC for the update checks
    ignore:
      - dependency-name: "null" 
        versions: ["1.x"] 

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows" 
    schedule:
      interval: "daily" 
      time: "03:00" 