# Jekyll configuration for HARDN-XDR documentation
title: HARDN-XDR
description: Comprehensive hardening and XDR security framework
url: "https://opensource-for-freedom.github.io"
baseurl: "/HARDN-XDR"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  modules:
    output: true
    permalink: /:collection/:name/
  docs:
    output: true
    permalink: /docs/:name/

# Exclude from processing
exclude:
  - node_modules/
  - frontend/
  - src/
  - debian/
  - .git/
  - .github/
  - "*.sh"
  - "*.log"
  - Gemfile
  - Gemfile.lock
  - package*.json
  - README.md
  - LICENSE
  - out/
  - .next/

# Include
include:
  - _pages
  - assets
  - badges

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "HARDN-XDR Team"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "modules"
    values:
      layout: "module"

# Site settings
author: "OpenSource-For-Freedom"
email: "contact@hardn-xdr.org"
github_username: "OpenSource-For-Freedom"

# SEO settings
lang: en_US
twitter:
  username: hardn_xdr
  card: summary

social:
  name: HARDN-XDR Team
  links:
    - https://github.com/OpenSource-For-Freedom/HARDN-XDR

# Navigation
navigation:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: Modules
    url: /modules/
  - title: Download
    url: /download/
  - title: GitHub
    url: https://github.com/OpenSource-For-Freedom/HARDN-XDR
