#!/bin/bash
set -e


chmod +x /usr/bin/hardn-main.sh



ln -sf /usr/bin/hardn-main.sh /usr/bin/hardn 
chmod +x /usr/bin/hardn


mkdir -p /etc/hardn


chown root:root /usr/bin/hardn-main.sh 
chmod 755 /usr/bin/hardn-main.sh 


exit 0