name: Changelog

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Generate full changelog into CHANGELOG.md
      - name: Generate CHANGELOG.md
        id: cliff_all
        uses: orhun/git-cliff-action@v4
        with:
          version: v2.6.1        # or "latest"
          config: .cliff.toml
          args: --all --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit CHANGELOG.md if changed (skip CI)
        run: |
          if ! git diff --quiet -- CHANGELOG.md; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add CHANGELOG.md
            git commit -m "docs(changelog): update after ${{ github.event.release.tag_name }} [skip ci]"
            git push
          else
            echo "No changes in CHANGELOG.md"
          fi

  sync-release-body:
    runs-on: ubuntu-latest
    needs: update-changelog
    steps:
      - name: Checkout (depth 0)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Generate notes for ONLY the published tag
      - name: Generate release notes for this tag
        id: cliff_tag
        uses: orhun/git-cliff-action@v4
        with:
          version: v2.6.1        # or "latest"
          config: .cliff.toml
          args: --tag "${{ github.event.release.tag_name }}" --verbose
        env:
          OUTPUT: RELEASE_NOTES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Update GitHub Release body from RELEASE_NOTES.md
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ github.event.release.tag_name }}
          bodyFile: RELEASE_NOTES.md
          token: ${{ secrets.GITHUB_TOKEN }}