name: ci

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    outputs:
      new_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest v1.1.x tag
        id: get_tag
        run: |
          latest_tag=$(git tag -l "v1.1.*" --sort=-v:refname | head -n 1)
          [ -z "$latest_tag" ] && latest_tag="v1.1.0"
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Extract patch version and bump
        id: bump
        run: |
          tag="${{ steps.get_tag.outputs.latest_tag }}"
          patch=$(echo "$tag" | sed 's/.*\.//')
          new_patch=$((patch + 1))
          new_tag="v1.1.$new_patch"
          echo "new_tag=$new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Install deps and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev debhelper fakeroot build-essential devscripts lintian gnupg whiptail

      - name: Set executable permissions
        run: |
          chmod +x install.sh debian/postinst hardn-xdr src/setup/hardn-main.sh
          find src/setup/modules -type f -name "*.sh" -exec chmod +x {} \;

      - name: Update changelog for ${{ matrix.arch }}
        run: |
          version="${{ steps.bump.outputs.new_tag }}"
          version="${version#v}"
          export DEBCHANGE_RELEASE_DATE="$(date -R)"
          arch="${{ matrix.arch }}"
          if [ ! -f debian/changelog ]; then touch debian/changelog; fi
          dch --newversion "$version" \
              "Automated release $version for architecture: $arch." \
              --distribution unstable \
              --force-distribution
          dch --release --force-distribution ""

      - name: Build package for ${{ matrix.arch }}
        run: |
          dpkg-buildpackage -us -uc
          sudo apt install -f -y

      - name: Rename .deb
        id: rename
        run: |
          version="${{ steps.bump.outputs.new_tag }}"
          version="${version#v}"
          deb_file=$(ls ../*.deb | head -n 1)
          new_name="hardn_${version}_${{ matrix.arch }}.deb"
          mv "$deb_file" "$new_name"
          echo "deb_file=$new_name" >> $GITHUB_OUTPUT

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: deb-${{ matrix.arch }}
          path: ${{ steps.rename.outputs.deb_file }}

  test-modules:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        module: [aide, auditd, audit_system, auto_updates, banner, binfmt, central_logging, chkrootkit, compilers, coredumps, debsums, deleted_files, dns_config, file_perms, firewire, grub, kernel_sec, network_protocols, ntp, pentest, process_accounting, purge_old_pkgs, rkhunter, secure_net, service_disable, shared_mem, stig_pwquality, suricata, ufw, unhide, unnecesary_services, usb]
      fail-fast: false
    steps:
      - name: Download .deb for ${{ matrix.arch }}
        uses: actions/download-artifact@v4
        with:
          name: deb-${{ matrix.arch }}
          path: .

      - name: Run module test for ${{ matrix.module }} on ${{ matrix.arch }}
        run: |
          echo "Testing module: ${{ matrix.module }} on arch ${{ matrix.arch }}" > result.log
          docker run --rm \
            -e SKIP_WHIPTAIL=1 \
            -v "$(pwd)/hardn_*.deb:/tmp/hardn.deb" \
            debian:stable-slim bash -c '
              set -e
              export DEBIAN_FRONTEND=noninteractive
              apt-get update && apt-get install -y sudo gnupg bash
              dpkg -i /tmp/hardn.deb || true
              apt-get install -f -y
              module="/usr/lib/hardn-xdr/src/setup/modules/${{ matrix.module }}.sh"
              if [ ! -f "$module" ]; then echo "Missing $module" && exit 1; fi
              chmod +x "$module"
              bash "$module"
            ' >> result.log 2>&1 || echo "FAIL: ${{ matrix.module }}" >> result.log

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: module-${{ matrix.arch }}-${{ matrix.module }}
          path: result.log

  test-deployment:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Download built .deb for ${{ matrix.arch }}
        uses: actions/download-artifact@v4
        with:
          name: deb-${{ matrix.arch }}
          path: .

      - name: Run full system test on ${{ matrix.arch }}
        run: |
          echo "Running full HARDN system test on ${{ matrix.arch }}" > full-run.log
          docker run --rm \
            -e SKIP_WHIPTAIL=1 \
            -v "$(pwd)/hardn_*.deb:/tmp/hardn.deb" \
            debian:stable-slim bash -c '
              set -e
              export DEBIAN_FRONTEND=noninteractive
              apt-get update && apt-get install -y sudo gnupg bash whiptail
              dpkg -i /tmp/hardn.deb || true
              apt-get install -f -y
              /usr/bin/hardn-xdr start || echo "Startup failed"
            ' >> full-run.log 2>&1 || echo "FAIL: full system run on ${{ matrix.arch }}" >> full-run.log

      - name: Upload full system test log
        uses: actions/upload-artifact@v4
        with:
          name: full-system-test-${{ matrix.arch }}
          path: full-run.log

  tag-and-release:
    needs: [build-and-test, test-modules, test-deployment]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags

      - name: Download all .deb artifacts
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Create and push new tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          tag="${{ needs.build-and-test.outputs.new_tag }}"
          if git rev-parse "$tag" >/dev/null 2>&1; then
            echo "Tag already exists, skipping"
          else
            git tag "$tag" -m "Release $tag"
            git push origin "$tag"
          fi

      - name: Move downloaded .debs to root for release
        run: |
          find . -type f -name "*.deb" -exec mv {} . \;

      - name: Create GitHub Release and upload .deb
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build-and-test.outputs.new_tag }}
          name: "Release ${{ needs.build-and-test.outputs.new_tag }}"
          body: |
            ![HARDN Logo](https://raw.githubusercontent.com/OpenSource-For-Freedom/HARDN/main/docs/assets/logo.png)

            **HARDN-XDR Automated Release**

            - **Version:** `${{ needs.build-and-test.outputs.new_tag }}`
            - **Architectures:** `amd64`, `arm64`
            - **Timestamp:** $(date -R)

            All modules tested in parallel. Full system test executed. Lintian validated.
          files: ./hardn_*.deb