name: ci

on:
  push:
    branches: ["main", "main-patch"]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    outputs:
      new_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest v1.1.x tag
        id: get_tag
        run: |
          latest_tag=$(git tag -l "v1.1.*" --sort=-v:refname | head -n 1)
          [ -z "$latest_tag" ] && latest_tag="v1.1.0"
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Extract patch version and bump
        id: bump
        run: |
          tag="${{ steps.get_tag.outputs.latest_tag }}"
          patch=${tag##*.}
          new_patch=$((patch + 1))
          new_tag="v1.1.$new_patch"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Install deps and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev debhelper fakeroot build-essential devscripts lintian gnupg whiptail

      - name: Set executable permissions
        run: |
          chmod +x debian/postinst hardn-xdr src/setup/hardn-main.sh
          find src/setup/modules -type f -name "*.sh" -exec chmod +x {} \;

      - name: Update changelog for ${{ matrix.arch }}
        run: |
          raw_tag="${{ steps.bump.outputs.new_tag }}"
          version="${raw_tag#v}"
          export DEBCHANGE_RELEASE_DATE="$(date -R)"
          arch="${{ matrix.arch }}"
          if [ ! -f debian/changelog ]; then touch debian/changelog; fi
          dch --newversion "$version" \
              "Automated release $version for architecture: $arch." \
              --distribution unstable \
              --force-distribution
          dch --release --force-distribution ""

      - name: Build package for ${{ matrix.arch }}
        env:
          DEBIAN_FRONTEND: noninteractive
          SKIP_WHIPTAIL: 1
        run: |
          dpkg-buildpackage -us -uc
          sudo apt install -f -y

      - name: Rename .deb
        id: rename
        run: |
          raw_tag="${{ steps.bump.outputs.new_tag }}"
          version="${raw_tag#v}"
          deb_file=$(ls ../*.deb | head -n 1)
          new_name="hardn_${version}_${{ matrix.arch }}.deb"
          mv "$deb_file" "$new_name"
          echo "deb_file=$new_name" >> $GITHUB_OUTPUT

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: deb-${{ matrix.arch }}
          path: ${{ steps.rename.outputs.deb_file }}

  test-deployment:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Register QEMU emulation
        uses: docker/setup-qemu-action@v3

      - name: Download built .deb for ${{ matrix.arch }}
        uses: actions/download-artifact@v4
        with:
          name: deb-${{ matrix.arch }}
          path: .

      - name: Simulate full HARDN deployment inside container
        run: |
          echo "Simulating full install for ${{ matrix.arch }}"
          cp hardn_*.deb ./hardn.deb
          docker run --rm -i --platform linux/${{ matrix.arch }} \
            -e SKIP_WHIPTAIL=1 \
            -e DEBIAN_FRONTEND=noninteractive \
            -e CI=true \
            -v "$(pwd)/hardn.deb:/tmp/hardn.deb" \
            debian:stable-slim bash -euxo pipefail -c '
              apt-get update
              apt-get install -y sudo bash gnupg curl whiptail
              dpkg -i /tmp/hardn.deb || true
              apt-get install -f -y
              echo "--- RUNNING HARDN DEPLOYMENT ---"
              /usr/bin/hardn-xdr --no-daemon --auto || echo "Launch failed"
            ' > full-run.log 2>&1

      - name: Upload full system test log
        uses: actions/upload-artifact@v4
        with:
          name: full-system-test-${{ matrix.arch }}
          path: full-run.log