name: ci

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest v1.1.x tag
        id: get_tag
        run: |
          latest_tag=$(git tag -l "v1.1.*" --sort=-v:refname | head -n 1)
          [ -z "$latest_tag" ] && latest_tag="v1.1.0"
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Extract patch version and bump
        id: bump
        run: |
          tag="${{ steps.get_tag.outputs.latest_tag }}"
          patch=$(echo "$tag" | sed 's/.*\.//')
          new_patch=$((patch + 1))
          new_tag="v1.1.$new_patch"
          echo "new_tag=$new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Install deps and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev debhelper fakeroot build-essential devscripts lintian gnupg whiptail

      - name: Set executable permissions
        run: |
          chmod +x install.sh debian/postinst hardn-xdr src/setup/hardn-main.sh
          find src/setup/modules -type f -name "*.sh" -exec chmod +x {} \;

      - name: Update changelog with real datetime
        run: |
          version="${{ steps.bump.outputs.new_tag }}"
          version="${version#v}"  # Strip 'v'
          export DEBCHANGE_RELEASE_DATE="$(date -R)"
          dch --newversion "$version" "Automated release $version" --distribution unstable --force-distribution
          dch --release --force-distribution ""

      - name: Build package
        run: |
          dpkg-buildpackage -us -uc
          sudo apt install -f -y

      - name: Move .deb
        id: rename
        run: |
          version="${{ steps.bump.outputs.new_tag }}"
          version="${version#v}"
          deb_file=$(ls ../*.deb | head -n 1)
          new_name="hardn_${version}_amd64.deb"
          mv "$deb_file" "$new_name"
          echo "deb_file=$new_name" >> $GITHUB_OUTPUT

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ${{ steps.rename.outputs.deb_file }}

  test-modules:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [aide, auditd, audit_system, auto_updates, banner, binfmt, central_logging, chkrootkit, compilers, coredumps, debsums, deleted_files, dns_config, file_perms, firewire, grub, kernel_sec, network_protocols, ntp, pentest, process_accounting, purge_old_pkgs, rkhunter, secure_net, service_disable, shared_mem, stig_pwquality, suricata, ufw, unhide, unnecesary_services, usb]
      fail-fast: false
    outputs:
      failed: ${{ steps.set-failure.outputs.failed }}
    steps:
      - name: Download .deb package
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: .

      - name: Run module test in container
        id: test
        run: |
          echo "Testing module: ${{ matrix.module }}" > result.log
          docker run --rm \
            -e SKIP_WHIPTAIL=1 \
            -v "$(pwd)/hardn_*.deb:/tmp/hardn.deb" \
            debian:stable-slim bash -c '
              set -e
              export DEBIAN_FRONTEND=noninteractive
              apt-get update && apt-get install -y sudo gnupg bash
              dpkg -i /tmp/hardn.deb || true
              apt-get install -f -y
              module="/usr/lib/hardn-xdr/src/setup/modules/${{ matrix.module }}.sh"
              if [ ! -f "$module" ]; then echo "Missing $module" && exit 1; fi
              chmod +x "$module"
              bash "$module"
            ' >> result.log 2>&1 || echo "FAIL: ${{ matrix.module }}" >> result.log

      - name: Upload test result
        uses: actions/upload-artifact@v4
        with:
          name: module-result-${{ matrix.module }}
          path: result.log

  tag-and-release:
    needs: [build-and-test, test-modules]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags

      - name: Download amd64 artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-amd64
          path: .

      - name: Download arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-arm64
          path: .

      - name: Create and push new tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          tag="${{ needs.build-and-test.outputs.new_tag }}"
          if git rev-parse "$tag" >/dev/null 2>&1; then
            echo "Tag already exists, skipping"
          else
            git tag "$tag" -m "Release $tag"
            git push origin "$tag"
          fi

      - name: Create GitHub Release and upload .deb
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build-and-test.outputs.new_tag }}
          name: "Release ${{ needs.build-and-test.outputs.new_tag }}"
          body: "Automated release for version ${{ needs.build-and-test.outputs.new_tag }}"
          files: |
            ./hardn_*_amd64.deb
            ./hardn_*_arm64.deb