  release:
    needs: [build-and-test, check-deployment-results]
    if: needs.check-deployment-results.outputs.passed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download built .debs
        uses: actions/download-artifact@v5
        with:
          path: release_assets

      - name: Verify logo and .debs
        run: |
          test -f docs/hardn.jpg
          test -f release_assets/deb-amd64/*.deb
          test -f release_assets/deb-arm64/*.deb

      - name: Build release notes
        run: |
          tag="${{ needs.build-and-test.outputs.new_tag }}"
          {
            echo "![HARDN-XDR Logo](https://raw.githubusercontent.com/OpenSource-For-Freedom/HARDN-XDR/${tag}/docs/hardn.jpg)"
            echo
            echo "Multi-architecture Debian-only release (AMD64/ARM64)."
            echo
            echo "### Direct wget/curl download links"
            echo '```bash'
            echo "wget https://github.com/OpenSource-For-Freedom/HARDN-XDR/releases/latest/download/hardn_latest_amd64.deb"
            echo "wget https://github.com/OpenSource-For-Freedom/HARDN-XDR/releases/latest/download/hardn_latest_arm64.deb"
            echo '```'
          } > release_notes.md

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ needs.build-and-test.outputs.new_tag }}"

          gh release create "$tag" \
            release_assets/deb-amd64/*.deb \
            release_assets/deb-arm64/*.deb \
            --title "Release $tag" \
            --notes-file release_notes.md