name: cis-debian

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"   # Mondays 04:00 UTC

permissions:
  contents: read

env:
  VM_RAM_MB: "2048"         
  VM_CPUS: "1"
  SSH_WAIT_SECS: "600"      
  VM_TIMEOUT: "30m"         
  ART_DIR: "cis-artifacts"
  DEBIAN12_IMAGE_URL: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2"

jobs:
  debian12-cis:
    name: Debian 12 — CIS (OpenSCAP) + Lynis
    runs-on: ubuntu-latest
    timeout-minutes: 150

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare artifacts dir
        run: mkdir -p "${{ env.ART_DIR }}/debian-12"

      - name: Install QEMU + helpers
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            qemu-system-x86 qemu-utils cloud-image-utils genisoimage \
            openssh-client curl jq ca-certificates \
            iproute2 iputils-ping xz-utils coreutils time

      - name: Write audit runner script
        shell: bash
        run: |
          cat > run_debian12_audits.sh <<'BASH'
          #!/usr/bin/env bash
          set -euo pipefail

          ART_BASE="${1:?artifact dir}"
          IMG_URL="${2:?debian12 cloud image url}"
          VM_RAM_MB="${VM_RAM_MB:-2048}"
          VM_CPUS="${VM_CPUS:-1}"
          SSH_WAIT_SECS="${SSH_WAIT_SECS:-600}"
          VM_TIMEOUT="${VM_TIMEOUT:-30m}"

          OS_NAME="debian-12"
          WORKDIR="$(pwd)/work-${OS_NAME}"
          mkdir -p "$WORKDIR" "$ART_BASE/${OS_NAME}"

          echo "[INFO] Downloading Debian 12 cloud image"
          IMG="$WORKDIR/disk.qcow2"
          curl -fsSL "$IMG_URL" -o "$WORKDIR/orig.img"
          qemu-img convert -O qcow2 "$WORKDIR/orig.img" "$IMG"
          qemu-img resize "$IMG" +6G || true

          echo "[INFO] Generating SSH key"
          SSH_DIR="$WORKDIR/ssh"; mkdir -p "$SSH_DIR"
          ssh-keygen -t ed25519 -f "$SSH_DIR/id_ed25519" -N "" -C "ci@hardn-xdr" >/dev/null

          echo "[INFO] Building cloud-init seed"
          CI_DIR="$WORKDIR/cloudinit"; mkdir -p "$CI_DIR"
          cat > "$CI_DIR/user-data" <<EOF
          #cloud-config
          users:
            - name: ci
              sudo: ALL=(ALL) NOPASSWD:ALL
              groups: sudo
              shell: /bin/bash
              ssh_authorized_keys:
                - $(cat "$SSH_DIR/id_ed25519.pub")
          package_update: true
          packages: [ ca-certificates ]
          runcmd:
            - [ sh, -c, "echo 'FS ready' > /root/firstboot.txt" ]
          EOF
          cat > "$CI_DIR/meta-data" <<EOF
          instance-id: ${OS_NAME}-ci
          local-hostname: ${OS_NAME}-ci
          EOF
          cloud-localds "$WORKDIR/seed.iso" "$CI_DIR/user-data" "$CI_DIR/meta-data"

          echo "[INFO] Launching QEMU (TCG; e1000 NIC)"
          SSH_PORT=$(shuf -i 2222-65000 -n 1)
          QEMU_LOG="$WORKDIR/qemu-console.log"
          qemu-system-x86_64 \
            -cpu max -smp "$VM_CPUS" -m "${VM_RAM_MB}" \
            -drive "if=virtio,file=$IMG,format=qcow2,cache=none,discard=unmap" \
            -cdrom "$WORKDIR/seed.iso" \
            -netdev user,id=n1,hostfwd=tcp::${SSH_PORT}-:22 \
            -device e1000,netdev=n1 \
            -display none -serial file:"$QEMU_LOG" -daemonize

          echo "[INFO] Waiting for SSH on port ${SSH_PORT} (<= ${SSH_WAIT_SECS}s)"
          deadline=$(( $(date +%s) + SSH_WAIT_SECS ))
          until ssh -i "$SSH_DIR/id_ed25519" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p "$SSH_PORT" ci@127.0.0.1 "echo OK" >/dev/null 2>&1; do
            if [ "$(date +%s)" -gt "$deadline" ]; then
              echo "[ERROR] VM did not become reachable via SSH"
              tail -n 200 "$QEMU_LOG" || true
              exit 1
            fi
            sleep 5
          done
          echo "[INFO] SSH reached, waiting extra 20s for cloud-init"
          sleep 20

          vm_ssh () {
            timeout "$VM_TIMEOUT" ssh -i "$SSH_DIR/id_ed25519" \
              -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              -p "$SSH_PORT" ci@127.0.0.1 "$@"
          }

          echo "[INFO] Installing tools (OpenSCAP, SSG, Lynis)"
          vm_ssh 'sudo DEBIAN_FRONTEND=noninteractive apt-get update || true'
          vm_ssh 'sudo DEBIAN_FRONTEND=noninteractive apt-get install -y openscap-scanner scap-security-guide lynis || true'

          echo "[INFO] Locating Debian SCAP datastream"
          DS_PATH="$(vm_ssh "ls /usr/share/xml/scap/ssg/content/ssg-debian12-ds.xml 2>/dev/null || true")"
          [ -z "$DS_PATH" ] && DS_PATH="$(vm_ssh "ls /usr/share/xml/scap/ssg/content/ssg-*-ds.xml | grep debian | head -n1" || true)"
          echo "[INFO] Using datastream: ${DS_PATH:-none}"

          CIS_PROFILE=""
          if [ -n "$DS_PATH" ]; then
            CIS_PROFILE="$(vm_ssh "oscap info '$DS_PATH' | awk '/^ +Profile/{print \$2,\$0}' | grep -i 'cis' | awk '{print \$1}' | head -n1" || true)"
          fi
          echo "[INFO] Selected profile: ${CIS_PROFILE:-none}"

          echo "[INFO] Running OpenSCAP evaluation"
          vm_ssh "sudo mkdir -p /tmp/osc"
          [ -n "$CIS_PROFILE" ] && vm_ssh "sudo oscap xccdf eval --profile '$CIS_PROFILE' --report /tmp/osc/report.html --results /tmp/osc/results.xml --results-arf /tmp/osc/results.arf --oval-results '$DS_PATH' || true"

          echo "[INFO] Collecting OpenSCAP artifacts"
          scp -i "$SSH_DIR/id_ed25519" -P "$SSH_PORT" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ci@127.0.0.1:/tmp/osc/* "$ART_BASE/${OS_NAME}/" || true

          echo "[INFO] Running Lynis"
          vm_ssh "sudo mkdir -p /tmp/lynis-out"
          vm_ssh "sudo lynis audit system --quiet --logfile /tmp/lynis-out/lynis.log --report-file /tmp/lynis-out/lynis-report.dat || true"

          echo "[INFO] Collecting Lynis artifacts"
          scp -i "$SSH_DIR/id_ed25519" -P "$SSH_PORT" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ci@127.0.0.1:/tmp/lynis-out/* "$ART_BASE/${OS_NAME}/" || true

          echo "[INFO] Shutting down VM"
          vm_ssh "sudo shutdown -h now" || true
          sleep 10 || true

          echo "[INFO] Done — artifacts under $ART_BASE/${OS_NAME}"
          exit 0
          BASH
          chmod +x run_debian12_audits.sh

      - name: Run Debian 12 CIS + Lynis
        run: |
          ./run_debian12_audits.sh "${{ env.ART_DIR }}" "${{ env.DEBIAN12_IMAGE_URL }}"

      - name: Upload all artifacts (OpenSCAP + Lynis)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debian-12-cis-and-lynis
          path: "${{ env.ART_DIR }}/debian-12"