name: Build and Test

on:
  push:
    branches:
      - main
      - dev-testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Build Debian package
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper
          dpkg-buildpackage -us -uc