name: Generate Insights # we see you :)

on:
  schedule:
    - cron: '0 3 * * *'  
  workflow_dispatch:

jobs:
  traffic-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch GitHub Views & Clones
        run: |
          mkdir -p public

          VIEW_JSON=$(curl -s -H "Authorization: token ${{ secrets.ACTION_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/traffic/views)

          CLONE_JSON=$(curl -s -H "Authorization: token ${{ secrets.ACTION_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/traffic/clones)

          VIEW_COUNT=$(echo "$VIEW_JSON" | jq '.count // 0')
          CLONE_COUNT=$(echo "$CLONE_JSON" | jq '.count // 0')

          echo "Views: $VIEW_COUNT, Clones: $CLONE_COUNT"

          cat <<EOF > public/traffic-views.json
          {
            "schemaVersion": 1,
            "label": "views",
            "message": "$VIEW_COUNT",
            "color": "blue"
          }
EOF

          cat <<EOF > public/traffic-clones.json
          {
            "schemaVersion": 1,
            "label": "clones",
            "message": "$CLONE_COUNT",
            "color": "green"
          }
EOF

      - name: Deploy traffic badges to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public