name: Generate GitHub Insights

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  traffic-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Generate traffic badge JSONs
        run: |
          mkdir -p public

          VIEW_JSON=$(curl -s -H "Authorization: token ${{ secrets.ACTION_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/traffic/views)

          CLONE_JSON=$(curl -s -H "Authorization: token ${{ secrets.ACTION_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/traffic/clones)

          VIEW_COUNT=$(echo "$VIEW_JSON" | jq '.count // 0')
          VIEW_UNIQUES=$(echo "$VIEW_JSON" | jq '.uniques // 0')
          CLONE_COUNT=$(echo "$CLONE_JSON" | jq '.count // 0')
          CLONE_UNIQUES=$(echo "$CLONE_JSON" | jq '.uniques // 0')

          if [ "$VIEW_COUNT" -ge 200 ]; then VIEW_COLOR="green"
          elif [ "$VIEW_COUNT" -ge 50 ]; then VIEW_COLOR="orange"
          else VIEW_COLOR="red"
          fi

          if [ "$CLONE_COUNT" -ge 100 ]; then CLONE_COLOR="blue"
          elif [ "$CLONE_COUNT" -ge 20 ]; then CLONE_COLOR="yellow"
          else CLONE_COLOR="red"
          fi

          cat <<EOF > public/traffic-views.json
          {
            "schemaVersion": 1,
            "label": "views",
            "message": "$VIEW_COUNT / $VIEW_UNIQUES",
            "color": "$VIEW_COLOR"
          }
          EOF

          cat <<EOF > public/traffic-clones.json
          {
            "schemaVersion": 1,
            "label": "clones",
            "message": "$CLONE_COUNT / $CLONE_UNIQUES",
            "color": "$CLONE_COLOR"
          }
          EOF

      - name: Deploy traffic badges to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public