name: Deploy Jekyll 

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 5 * * 5'
  workflow_dispatch:

# Permissions for the job token; we still supply ACTION_TOKEN to steps that need write.
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 1) Make sure package-lock.json matches package.json and open a PR if it doesn't
  lockfile:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: chore/update-lockfile
    steps:
      - name: Checkout (with PAT)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Regenerate package-lock.json
        run: |
          set -e
          test -f package.json || { echo "package.json missing"; exit 1; }
          rm -rf node_modules package-lock.json
          npm cache verify
          npm install --package-lock-only
          # sanity check the lock
          rm -rf node_modules
          npm ci

      - name: Create/Update PR with new lockfile (using PAT)
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          commit-message: "chore(lock): sync package-lock.json with package.json"
          title: "chore(lock): sync package-lock.json with package.json"
          body: |
            CI regenerated **package-lock.json** from the committed **package.json**.
            If checks pass, merge this PR to keep the lockfile in sync.
          labels: dependencies
          delete-branch: false
          draft: false

      - name: Stop if PR was created/updated
        if: steps.cpr.outputs.pull-request-operation != ''
        run: |
          echo "Lockfile changed; PR ${{
            steps.cpr.outputs.pull-request-number
          }} opened/updated at ${{
            steps.cpr.outputs.pull-request-url
          }}. Merge it, then the build will run on main."
          exit 0

  # 2) Build only after changes are on main (i.e., after you merge the PR)
  build:
    if: github.ref == 'refs/heads/main'
    needs: lockfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (read-only is fine)
        uses: actions/checkout@v4

      - name: Detect Node/Next presence
        run: |
          needs_node=false
          next_enabled=false
          if [ -f package.json ] || [ -f package-lock.json ]; then needs_node=true; fi
          if [ -d "pages" ] || [ -d "components" ] || [ -f "next.config.js" ]; then next_enabled=true; fi
          echo "NEEDS_NODE=$needs_node" >> "$GITHUB_ENV"
          echo "NEXT_JS_ENABLED=$next_enabled" >> "$GITHUB_ENV"

      - name: Setup Node.js
        if: env.NEEDS_NODE == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package.json
            package-lock.json

      - name: Install deps
        if: env.NEEDS_NODE == 'true'
        run: npm ci

      - name: Verify Next CLI
        if: env.NEXT_JS_ENABLED == 'true'
        run: npx --yes next --version

      - name: Generate traffic badges
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          mkdir -p _site/badges
          VIEW_JSON=$(curl -s -H "Authorization: token ${{ secrets.ACTION_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/traffic/views || echo '{"count":0,"uniques":0}')
          CLONE_JSON=$(curl -s -H "Authorization: token ${{ secrets.ACTION_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/traffic/clones || echo '{"count":0,"uniques":0}')
          VIEW_COUNT=$(echo "$VIEW_JSON" | jq -r '.count // 0'); VIEW_UNIQUES=$(echo "$VIEW_JSON" | jq -r '.uniques // 0')
          CLONE_COUNT=$(echo "$CLONE_JSON" | jq -r '.count // 0'); CLONE_UNIQUES=$(echo "$CLONE_JSON" | jq -r '.uniques // 0')
          if [ "$VIEW_COUNT" -ge 200 ]; then VIEW_COLOR="green"; elif [ "$VIEW_COUNT" -ge 50 ]; then VIEW_COLOR="orange"; else VIEW_COLOR="red"; fi
          if [ "$CLONE_COUNT" -ge 100 ]; then CLONE_COLOR="blue"; elif [ "$CLONE_COUNT" -ge 20 ]; then CLONE_COLOR="yellow"; else CLONE_COLOR="red"; fi
          cat > _site/badges/traffic-views.json <<EOF
          { "schemaVersion":1,"label":"views","message":"$VIEW_COUNT / $VIEW_UNIQUES","color":"$VIEW_COLOR" }
          EOF
          cat > _site/badges/traffic-clones.json <<EOF
          { "schemaVersion":1,"label":"clones","message":"$CLONE_COUNT / $CLONE_UNIQUES","color":"$CLONE_COLOR" }
          EOF

      - name: Build Next.js (static export)
        id: nextexport
        if: env.NEXT_JS_ENABLED == 'true'
        run: |
          set -e
          npm run export
          mkdir -p _site
          cp -r out/* _site/ || true
          touch _site/.nojekyll
          echo "exported=true" >> "$GITHUB_OUTPUT"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        if: steps.nextexport.outputs.exported != 'true'
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # 3) Deploy when main is built
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4