name: Test HARDN with Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight UTC

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          activate-environment: test-env
          environment-file: environment.yml

      - name: Set PYTHONPATH to include all directories
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Verify flake8 installation
        run: |
          conda run -n test-env flake8 --version

      - name: Lint all Python files with flake8
        run: |
          conda run -n test-env flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          conda run -n test-env flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Verify pytest installation
        run: |
          conda run -n test-env pytest --version

      - name: Run all tests in all Python files
        run: |
          conda run -n test-env pytest -v $(find . -type f -name "*.py")