name: "CodeQL Security Scanning for Bash"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * 7' # Weekly scan on Sundays

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: "bash" # Explicitly enable bash analysis

    - name: Build CodeQL Database
      run: |
        echo "Building the CodeQL database..."
        # Adjust these commands to build your project if necessary
        # For example, install dependencies or compile code
        bash --version # Ensure bash is available
        echo "No specific build steps required for bash scripts."

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/security-tests"

    - name: Upload CodeQL Results
      uses: actions/upload-artifact@v3
      with:
        name: codeql-results
        path: codeql-results/

    - name: Create Issue for Security Findings
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Creating GitHub Issue for Security Findings..."
        ISSUE_TITLE="CodeQL Security Findings"
        ISSUE_BODY="CodeQL has identified potential security issues in the repository:\n\n"
        for finding in codeql-results/*.log; do
          ISSUE_BODY="$ISSUE_BODY$(basename "$finding"):\n$(cat "$finding")\n\n"
        done
        echo -e "$ISSUE_BODY" > issue_body.txt
        gh issue create --title "$ISSUE_TITLE" --body-file issue_body.txt