name: Test CI Fix

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/ci.yml'

jobs:
  test-ubuntu-resilience:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        distro: [ubuntu]
    steps:
      - name: Test Ubuntu Package Update Resilience
        run: |
          echo "Testing apt-get update resilience..."
          
          # Simulate the same retry logic as in main CI
          for attempt in 1 2 3; do
            echo "Attempt $attempt: Updating package lists..."
            if apt-get update; then
              echo "✅ Package update successful"
              break
            elif [ $attempt -eq 3 ]; then
              echo "⚠️  All update attempts failed, but continuing with existing package cache"
              echo "WARNING: Using potentially stale package cache due to mirror issues"
            else
              echo "Update failed, retrying in 5 seconds..."
              sleep 5
            fi
          done
          
          echo "✅ Resilience test completed successfully"

  validate-ci-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate CI YAML Syntax
        run: |
          python3 -c "import yaml; yaml.safe_load(open('.github/workflows/ci.yml', 'r'))" 
          echo "✅ CI YAML syntax is valid"
      
      - name: Check CI Logic
        run: |
          echo "Checking CI workflow improvements..."
          
          # Check for retry logic
          if grep -q "for attempt in 1 2 3" .github/workflows/ci.yml; then
            echo "✅ Retry logic found"
          else
            echo "❌ Retry logic missing"
            exit 1
          fi
          
          # Check for continue-on-error
          if grep -q "continue-on-error: true" .github/workflows/ci.yml; then
            echo "✅ Error resilience found"
          else
            echo "❌ Error resilience missing"
            exit 1
          fi
          
          echo "✅ All CI improvements validated"