name: Update Debian Changelog

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.2.3

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_NAME#v}"  # Remove 'v' prefix
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "::set-output name=new_tag::$TAG_NAME"

      - name: Install devscripts (for dch)
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts

      - name: Update changelog with new version
        run: |
          export DEBFULLNAME="Tim Burns"
          export DEBEMAIL="cyborgcreations01@gmail.com"
          dch --newversion "$VERSION" "Automated release $VERSION" \
              --distribution unstable --force-distribution
          dch --release --force-distribution ""

      - name: Commit updated changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add debian/changelog
          git commit -m "chore: update changelog for $VERSION" || echo "No changes to commit"
          git push origin HEAD
