name: Validate Package Dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate and Update Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write    
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    

      - name: Update system packages
        run: |
          set -o pipefail
          sudo apt-get update || { echo "::error::apt-get update failed"; exit 1; }

      - name: Validate and create progs.csv if missing
        id: csv
        run: |
          if [ ! -f "progs.csv" ]; then
            echo "progs.csv file not found. Creating one with proper headers."
            echo "name,version,debian_min_version,debian_codenames" > progs.csv
            echo "# Add your package dependencies here" >> progs.csv
            echo "# Example: curl,latest,12,\"bookworm\"" >> progs.csv
            echo "changes_made=true" >> $GITHUB_OUTPUT
          else
            echo "progs.csv exists. Validating format..."
            # Check if file has proper headers
            header=$(head -n 1 progs.csv)
            if [[ "$header" != "name,version,debian_min_version,debian_codenames" ]]; then
              echo "::error::progs.csv header format is incorrect. Expected: name,version,debian_min_version,debian_codenames"
              echo "::error::Found: $header"
              echo "Correcting header to expected format..."
              sed -i '1s/.*/name,version,debian_min_version,debian_codenames/' progs.csv
              echo "Header corrected successfully."
            fi
            
            # Count non-comment, non-empty lines
            package_count=$(grep -E -v '^(#|[[:space:]]*$|name,version)' progs.csv | wc -l)
            echo "Found $package_count package entries in progs.csv"
            
            if [ "$package_count" -eq 0 ]; then
              echo "::warning::No package entries found in progs.csv"
            fi
            
            echo "changes_made=false" >> $GITHUB_OUTPUT
          fi

      - name: Stage changes for PR creation
        if: steps.csv.outputs.changes_made == 'true'
        run: |
          git add progs.csv

      - name: No changes needed
        if: steps.csv.outputs.changes_made == 'false'
        run: |
          echo "✅ progs.csv exists and validation completed successfully"
          echo "No pull request needed as no changes were made"

      - name: Create Pull Request
        if: steps.csv.outputs.changes_made == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Create progs.csv with proper format"
          branch: update-packages-${{ github.run_id }}
          title: "Create missing progs.csv file"
          body: |
            This PR creates the missing progs.csv file with the proper format.
            
            ## Changes
            - Created progs.csv with correct headers: name,version,debian_min_version,debian_codenames
            - Added example comments for adding package dependencies
            - File is ready for package dependency definitions
            
            ## Next Steps
            Add your package dependencies to this file following the format:
            ```
            package_name,version,debian_min_version,debian_codenames
            ```
          delete-branch: true
