name: Validate Package Dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate and Update Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write    
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    

      - name: Update system packages
        run: |
          set -o pipefail
          sudo apt-get update || { echo "::error::apt-get update failed"; exit 1; }

      - name: Create progs.csv if missing
        id: csv
        run: |
          if [ ! -f "progs.csv" ]; then
            echo "progs.csv file not found. Creating one."
            echo "name,version" > progs.csv
            echo "changes_made=false" >> $GITHUB_OUTPUT
            exit 0
          fi

      - name: Configure git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or switch to unique update branch
        run: |
          BRANCH_NAME="update-packages-${GITHUB_RUN_ID}"
          git checkout -B "$BRANCH_NAME"

      - name: Commit any changes
        run: |
          git add progs.csv
          git diff --cached --quiet || git commit -m "Update progs.csv if missing"
        continue-on-error: true   

      - name: Push changes to unique update branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="update-packages-${GITHUB_RUN_ID}"
          git push --set-upstream origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update progs.csv if missing"
          branch: update-packages-${{ github.run_id }}
          title: "Update progs.csv if missing"
          body: "This PR updates or creates the progs.csv file if it was missing."
