name: "Xanitizer Security Analysis"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '37 6 * * 4'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  xanitizer-security-analysis:
    permissions:
      contents: read
      security-events: write 
      actions: read 
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Compile Java code
        run: mvn -B compile

      - name: Install JavaScript libraries
        run: npm install

      # Run the security analysis with default settings
      - name: Xanitizer Security Analysis
        uses: RIGS-IT/xanitizer-action@87d13138fb113b727cbe040c744a15a2b4fe5316
        with:
          license: ${{ secrets.XANITIZER_LICENSE }}

      - uses: actions/upload-artifact@v4
        with:
          name: Xanitizer-Reports
          path: |
            *-Findings-List.pdf
            *-Findings-List.sarif

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: Xanitizer-Findings-List.sarif
